### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by JiaminXuan** [h2oai/h2o-tutorials#11]
would like to see a python version of h2o stacking

**Comment by ledell** [comment]
@JiaminXuan Stacking in Python has been added to H2O in this [upcoming PR](https://github.com/h2oai/h2o-3/pull/554).  Code examples exist [here](https://github.com/h2oai/h2o-3/tree/ensembles/h2o-py/tests/testdir_algos/stackedensemble).  I will close this issue when we merge the "ensembles" branch to master.

**Comment by ledell** [comment]
Stacking was added to the H2O backend and is now in all the APIs, including Python.  Docs [here](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/stacked-ensembles.html).
