### ISSUE TITLE
Duplicate code in "Intro to ML" tutorial

### ISSUE THREAD

**Issue by mikeumus** [h2oai/h2o-tutorials#117]
Is the "Introduction to Machine Learning" tutorial somewhere in here?

There's some duplicate code a the end of this first code-block here on this page:
https://h2oai.github.io/tutorials/introduction-to-machine-learning-with-h2o-part-1/#8

<img width="857" alt="Screen Shot 2019-12-10 at 2 43 02 PM" src="https://user-images.githubusercontent.com/57934/70562972-6513ed00-1b5b-11ea-8118-44cc3a635e81.png">

**Comment by Castro38** [comment]
Hi @mikeumus, thank you for checking out our tutorial and letting us know about the duplicate code.  The tutorial has been updated without the duplicate line of code.

https://h2oai.github.io/tutorials/introduction-to-machine-learning-with-h2o-part-1/#8

Please feel free to share any future feedback regarding tutorials at our tutorials GitHub Repo: https://github.com/h2oai/tutorials/issues.

Ana
