### ISSUE TITLE
Will H2ORuleFit be added to h2o-3

### ISSUE THREAD

**Issue by davidgibsonp** [h2oai/h2o-tutorials#127]
First off big thank you to all H2O Contributors!!

So I stumbled upon this a new the H2ORuleFit model found [here](https://github.com/h2oai/h2o-tutorials/tree/54981a520d93718012a17cdad2c774aad1f61070/best-practices/explainable-models). I have used the RuleFit model in DataRobot but really want to be able to implement in my own notbooks via H20. 

My question is if/when will [H2ORuleFit](https://github.com/h2oai/h2o-tutorials/blob/54981a520d93718012a17cdad2c774aad1f61070/best-practices/explainable-models/rulefit.py#L10) model make it into H2O--<s>2</s>**3**?

Thanks!!

@meganjkurka

**Comment by tomkraljevic** [comment]
[ This was probably a typo, but just to be clear, H2O-2 has not been maintained for years.  H2O-3 is maintained. ]

The example added by @meganjkurka is already using a thin layer of python on top of H2O-3.  Can you be more specific about are you are interested in here?

**Comment by davidgibsonp** [comment]
Oh yes my mistake I meant 3. Hmm I was not able to find the **H2ORuleFit** module when [searching in h2o-3](https://github.com/h2oai/h2o-3/search?q=H2ORuleFit&unscoped_q=H2ORuleFit).

Oh wait I see RuleFit on the Roadmap for [H2O 3.32 - Spring 2020 (Q2/2020)](https://github.com/h2oai/h2o-3/blob/97b6634a9556befa38c865de6103c1562e5d0ea9/README.md#h2o-332---spring-2020-q22020) in the README. Probably just have to wait.

Thank you!
