### ISSUE TITLE
Video link

### ISSUE THREAD

**Issue by Shawcs** [h2oai/h2o-tutorials#16]
On the README for "h2o-tutorials/tutorials/streaming/storm/" at the end you put "Here's a short video showing what it looks like all together." But the link to the vieo is dead. Little issue but I think the video can bring a lot of information.

**Comment by ledell** [comment]
Thanks @Shawcs, we will take a look. cc @angela0xdata

**Comment by angela0xdata** [comment]
@Shawcs, thank you for pointing this out. I'll update the readme with the current link:
https://www.youtube.com/watch?v=NTUo5MyS6qE

**Comment by ledell** [comment]
Changes have been merged.  https://github.com/h2oai/h2o-tutorials/pull/17  Thanks @Shawcs and @angela0xdata !
