### ISSUE TITLE
training_data.csv in storm streaming tutorial a 'Numbers' binary file

### ISSUE THREAD

**Issue by CamCairns** [h2oai/h2o-tutorials#19]
The training_data.csv is not a csv file (can't head like the tutorial README suggests and running the example.R script errors when the file is attempted to be imported). 

A little investigation shows that it is a binary format belonging to Number (Mac spreadsheet software). Opening and exporting as a csv file resolves the problems.

**Comment by ledell** [comment]
@CamCairns Thanks for the note.  @angela0xdata Do you think you can convert the file to a proper csv and update the tutorial?

**Comment by angela0xdata** [comment]
@CamCairns @ledell, I exported the numbers file to CSV. 
I verified locally that "head -n 20 training_data.csv" shows the top 20 rows, and "R -f example.R" runs without errors.

**Comment by ledell** [comment]
Thanks @angela0xdata, I'll close this now.
