### ISSUE TITLE
Link in Intro to R outdated

### ISSUE THREAD

**Issue by hfrick** [h2oai/h2o-tutorials#22]
The link <http://www.h2o.ai/download/h2o/r> in the [Intro to R](https://github.com/h2oai/h2o-tutorials/blob/master/h2o-open-tour-2016/chicago/intro-to-h2o.R)

`# The latest version is always here: http://www.h2o.ai/download/h2o/r`

leads to [version 3.10.0.10](http://h2o-release.s3.amazonaws.com/h2o/rel-turing/10/index.html) instead of the latest version.

**Comment by angela0xdata** [comment]
Thank you for pointing this out. I have updated the link location for the latest version in that file, and you can get the latest version of R by clicking the R tab here: http://h2o-release.s3.amazonaws.com/h2o/latest_stable.html.

**Comment by ledell** [comment]
@angela0xdata Thanks for updating the tutorial.  We also link to http://www.h2o.ai/download/h2o/r in many slidedecks, so we should fix the actual URL redirect too.  I'll follow up with @teroneward and close this ticket when it's fixed.

**Comment by ledell** [comment]
Fixed.  Thanks, @teroneward!
