### ISSUE TITLE
unable to deep copy a h20 dataframe

### ISSUE THREAD

**Issue by yonghuajiang** [h2oai/h2o-tutorials#37]
H2O does not seem to have a function to deep copy dataframe yet. 

```
df_orig = h2o.import_file(path = "titanic.csv")
print df_orig[0:3,'age']

df_new = df_orig
df_new[0:3,'age'] = 2
print df_orig[0:3,'age']


age
--
29
0.9167
2


age
--
2
2
2
```

**Comment by ledell** [comment]
You're looking for the `h2o.deep_copy()` method, documented [here](http://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/h2o.html#h2o.deep_copy).
