### ISSUE TITLE
How to distinguish between classifier and regressor in the h2o models?

### ISSUE THREAD

**Issue by NagabhushanS** [h2oai/h2o-tutorials#46]
H2O provides H20GradientBoostingEstimator which does not provide any field for specifying whether it is a classifier or regressor. Also the predict method returns.only real values and thus no labels when predicted on a classification based dataset. So how do we distinguish or specify whether the model is a classifier or regressor in all the h2o models?

**Comment by ledell** [comment]
H2O will decide to do classification or regression based on the data type of the response column.  If it's encoded as a categorical (aka factor/enum), then it will do classification.  If it's numeric, then it will do regression.  There's an example of this [here](https://github.com/h2oai/h2o-tutorials/blob/master/h2o-open-tour-2016/chicago/intro-to-h2o.ipynb), look for the line that says:
```
data['bad_loan'] = data['bad_loan'].asfactor()
```

**Comment by kasuteru** [comment]
Since this is at the top of my Google search, just an additional question, I'll ask this here as well: What happens when the column is a Boolean?

**Comment by ledell** [comment]
@kasuteru H2O frames do not have a specific boolean type.  They would be a categorical column with two levels, so you would also need to convert to a factor type.
