### ISSUE TITLE
GBM fundamentals fail

### ISSUE THREAD

**Issue by EngrStudent** [h2oai/h2o-tutorials#5]
GBM need low learning rates, not high ones.  This means it takes a long time (aka high number of tree-augments to get down in error).  It is the Achilles-heel of the algorithm.  

Check out slide 25 (and the rest of them) here:
http://www.slideshare.net/DataRobot/gradient-boosted-regression-trees-in-scikitlearn

Check out slide 26 here:
http://www.slideshare.net/0xdata/gbm-27891077

**Comment by mlandry22** [comment]
That comment is accurate, despite seeming counter-intuitive: the validation performance of that model is better with a higher learning rate. The context is that when running that data set, you need either a higher learning rate or more trees as compared to the default configuration (50 trees, 0.1 learning rate). Effectively the GBM with default parameters is underfit. To fit a more accurate model with the same run time, increasing the learning rate is the right decision.

I will try to change the comment to emphasize the desire to keep the run time in check, which is a reasonable goal for practical purposes.

Regarding the overall comment about the learning rate, keep in mind it is always a tradeoff between learning rate, trees, and depth. Most often the difference between the best-fit GBM at 0.05 and 0.01 is fairly small, and for most problems insignificant.

For reference,  I believe you're talking about this comment block, from lines 101 - 118:
```r
## This default GBM is much worse than our original random forest.
## The GBM is far from converging, so there are three primary knobs to adjust
##  to get our performance up if we want to keep a similar run time.
## 1: Adding trees will help. The default is 50.
## 2: Increasing the learning rate will also help. The contribution of each
##  tree will be stronger, so the model will move further away from the
##  overall mean.
## 3: Increasing the depth will help. This is the parameter that is the least
##  straightforward. Tuning trees and learning rate both have direct impact
##  that is easy to understand. Changing the depth means you are adjusting
##  the "weakness" of each learner. Adding depth makes each tree fit the data
##  closer. 
```
