### ISSUE TITLE
[tutorial Request] : any tutorials to train h20 deep neural network with audio features (mfcc's) 

### ISSUE THREAD

**Issue by manbharae** [h2oai/h2o-tutorials#51]
can h20.ai be used to work with audio features like mfcc's/plp's/rmse/ etc? 
I want to train a h2o neural network using audio features. Please point me to tutorials.

**Comment by ledell** [comment]
We don't have any tutorials like this, sorry.  As long as you can convert the auto to numeric features, then you can use H2O Deep Learning (or any other supervised algorithm).

Last time I checked there was not very much open source software for converting audio to MFCCs, but if you came across any in R or Python and wrote the data-prep piece, then it would be easy to apply H2O DL to this and make a tutorial.
