### ISSUE TITLE
grid-search-model-selection.ipynb content broken

### ISSUE THREAD

**Issue by gigglegrig** [h2oai/h2o-tutorials#70]
h2o-tutorials/h2o-open-tour-2016/chicago/grid-search-model-selection.ipynb The jupyter notebook cannot be rendered by Github, nor could it be opened with local jupyter after been downloaded.

**Comment by angela0xdata** [comment]
@gigglegrig thank you for pointing this out. The file has been fixed and can now be viewed in GitHub. Please let me know if you still have any issues with this.
