### ISSUE TITLE
Fail to start H2o cluster in docker container

### ISSUE THREAD

**Issue by tobegit3hub** [h2oai/h2o-tutorials#84]
Now we try to use H2o to construct training cluster. It is easy to use by running `java -jar ./h2o.jar` and we can setup the cluster with simple `flatfile.txt` which contain multiple ip and ports.

But we found that it is impossible to setup the h2o cluster within docker containers. Although we can start multiple containers to run `java -jar ./h2o.jar` and add the prepared `flatfile.txt`, the h2o process will try to bind local(container's eth0) ip which is different from the one in `flatfile.txt`. We can `java -jar ./h2o.jar -ip $ip` to set the one which is in `flatfile.txt` but h2o instance is not able to run without this "external" ip.

<img width="927" alt="wechatimg34" src="https://user-images.githubusercontent.com/2715000/47484515-72deb400-d86e-11e8-9483-7a192203d7cb.png">

**Comment by tomkraljevic** [comment]
it works if you use “docker run —network=host ...”

tom

On Oct 25, 2018, at 9:56 AM, tobe <notifications@github.com<mailto:notifications@github.com>> wrote:


Now we try to use H2o to construct training cluster. It is easy to use by running java -jar ./h2o.jar and we can setup the cluster with simple flatfile.txt which contain multiple ip and ports.

But we found that it is impossible to setup the h2o cluster within docker containers. Although we can start multiple containers to run java -jar ./h2o.jar and add the prepared flatfile.txt, the h2o process will try to bind local(container's eth0) ip which is different from the one in flatfile.txt. We can java -jar ./h2o.jar -ip $ip to set the one which is in flatfile.txt but h2o instance is not able to run without this "external" ip.

[wechatimg34]<https://user-images.githubusercontent.com/2715000/47484515-72deb400-d86e-11e8-9483-7a192203d7cb.png>

**Comment by tobegit3hub** [comment]
Thanks @tomkraljevic . It seems H2o needs to broadcast the packages and we should not expose specified ports to make it works.
