### ISSUE TITLE
Can not load GBM_RandomForest_Example.ipynb in browser

### ISSUE THREAD

**Issue by cooleel** [h2oai/h2o-tutorials#87]
Can't load this in browser
https://github.com/h2oai/h2o-tutorials/blob/master/tutorials/gbm-randomforest/GBM_RandomForest_Example.ipynb

**Comment by angela0xdata** [comment]
Hi Cooleel. Thank you for pointing this out. I merged a fix, and I'm able to see this and the GLM notebook. (These were missing \ in a quoted string.)

**Comment by cooleel** [comment]
Great! It works. Thanks.

> Hi Cooleel. Thank you for pointing this out. I merged a fix, and I'm able to see this and the GLM notebook. (These were missing \ in a quoted string.)
