### ISSUE TITLE
What is TargetEncoder?

### ISSUE THREAD

**Issue by Erlemar** [h2oai/h2o-tutorials#92]
Hello!
I have a question:
What is TargetEncoder in this line:
```python
from h2o.targetencoder import TargetEncoder
```
?
I can't import it and can find no code for it.

**Comment by deil87** [comment]
Hi @Erlemar! This class was added in 3.22.0.1 version. Here is the link on github https://github.com/h2oai/h2o-3/blob/master/h2o-py/h2o/targetencoder.py . So you need to use the latest version of h2o-3

**Comment by Erlemar** [comment]
Thank you for your answer!
