### ISSUE TITLE
H2OValueError: Unknown parameter keep_cross_validation_models = True

### ISSUE THREAD

**Issue by TheXu** [h2oai/h2o-tutorials#93]
Running through the Python example code given here:
http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/keep_cross_validation_models.html

and I get a "H2OValueError: Unknown parameter keep_cross_validation_models = True" 

My h2o version is 3.18.0.2, h2o-py version is 3.18.0.2

**Comment by cooleel** [comment]
Took a look at source code. I think this line:
`cars_gbm = H2OGradientBoostingEstimator(keep_cross_validation_models = True, nfolds = 5, seed = 1234)`
should be:
`cars_gbm = H2OGradientBoostingEstimator(keep_cross_validation_predictions = True, nfolds = 5, seed = 1234)`

**Comment by ledell** [comment]
The `keep_cross_validation_models` parameter was introduced in 3.22.  It's okay that it's there.
